# Generated by Django 3.1.2 on 2020-11-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_sizevarient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SizeVarient',
            new_name='SizeVariant',
        ),
    ]
